# GoBarber
version: '3.6'

services:
  postgres:
    image: postgres:11.5-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

  redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  # api:
  #   build: .
  #   volumes:
  #     - ./:/home/node/app
  #   ports:
  #     - '3333:3333'
  #   command: 'yarn dev'
  #   links:
  #     - postgres
  #     - redis
  #     - mongo

  # queue:
  #   build: .
  #   volumes:
  #     - ./:/home/node/app
  #   command: 'yarn queue'
  #   links:
  #     - postgres
  #     - redis
  #     - mongo

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  mongo-data:
    driver: local
